'use client';
import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { useToast } from "@/hooks/use-toast";
import { Copy, RefreshCw, Smile, ArrowRight } from "lucide-react";

const EmojiReplacer = () => {
  const [inputText, setInputText] = useState("");
  const [outputText, setOutputText] = useState("");
  const [replacementMode, setReplacementMode] = useState<"text" | "emoji" | "custom">("text");
  const [customReplacement, setCustomReplacement] = useState("");
  const [preserveShortcodes, setPreserveShortcodes] = useState(true);
  const [caseMode, setCaseMode] = useState<"keep" | "lower" | "upper" | "title">("keep");
  const [addBrackets, setAddBrackets] = useState(false);
  const { toast } = useToast();

  const emojiToText: Record<string, string> = {
    '😀': 'grinning',
    '😃': 'smiley',
    '😄': 'smile',
    '😁': 'grin',
    '😆': 'laughing',
    '😅': 'sweat_smile',
    '🤣': 'rolling_on_the_floor_laughing',
    '😂': 'joy',
    '🙂': 'slightly_smiling_face',
    '🙃': 'upside_down_face',
    '😉': 'wink',
    '😊': 'blush',
    '😇': 'innocent',
    '🥰': 'smiling_face_with_3_hearts',
    '😍': 'heart_eyes',
    '🤩': 'star_struck',
    '😘': 'kissing_heart',
    '😗': 'kissing_face',
    '☺️': 'smiling_face',
    '😚': 'kissing_face_with_closed_eyes',
    '😙': 'kissing_face_with_smiling_eyes',
    '🥲': 'smiling_face_with_tear',
    '😋': 'face_savoring_food',
    '😛': 'face_with_tongue',
    '😜': 'winking_face_with_tongue',
    '🤪': 'zany_face',
    '😝': 'squinting_face_with_tongue',
    '🤑': 'money_mouth_face',
    '🤗': 'hugging_face',
    '🤭': 'face_with_hand_over_mouth',
    '🤫': 'shushing_face',
    '🤔': 'thinking_face',
    '🤐': 'zipper_mouth_face',
    '🤨': 'face_with_raised_eyebrow',
    '😐': 'neutral_face',
    '😑': 'expressionless_face',
    '😶': 'face_without_mouth',
    '😏': 'smirking_face',
    '😒': 'unamused_face',
    '🙄': 'face_with_rolling_eyes',
    '😬': 'grimacing_face',
    '🤥': 'lying_face',
    '😔': 'pensive_face',
    '😪': 'sleepy_face',
    '🤤': 'drooling_face',
    '😴': 'sleeping_face',
    '😷': 'face_with_medical_mask',
    '🤒': 'face_with_thermometer',
    '🤕': 'face_with_head_bandage',
    '🤢': 'nauseated_face',
    '🤮': 'face_vomiting',
    '🤧': 'sneezing_face',
    '🥵': 'hot_face',
    '🥶': 'cold_face',
    '🥴': 'woozy_face',
    '😵': 'dizzy_face',
    '🤯': 'exploding_head',
    '🤠': 'cowboy_hat_face',
    '🥳': 'partying_face',
    '🥸': 'disguised_face',
    '😎': 'smiling_face_with_sunglasses',
    '🤓': 'nerd_face',
    '🧐': 'face_with_monocle',
    '😕': 'confused_face',
    '😟': 'worried_face',
    '🙁': 'slightly_frowning_face',
    '☹️': 'frowning_face',
    '😮': 'face_with_open_mouth',
    '😯': 'hushed_face',
    '😲': 'astonished_face',
    '😳': 'flushed_face',
    '🥺': 'pleading_face',
    '😦': 'frowning_face_with_open_mouth',
    '😧': 'anguished_face',
    '😨': 'fearful_face',
    '😰': 'anxious_face_with_sweat',
    '😥': 'sad_but_relieved_face',
    '😢': 'crying_face',
    '😭': 'loudly_crying_face',
    '😱': 'face_screaming_in_fear',
    '😖': 'confounded_face',
    '😣': 'persevering_face',
    '😞': 'disappointed_face',
    '😓': 'downcast_face_with_sweat',
    '😩': 'weary_face',
    '😫': 'tired_face',
    '🥱': 'yawning_face',
    '😤': 'face_with_steam_from_nose',
    '😡': 'pouting_face',
    '😠': 'angry_face',
    '🤬': 'face_with_symbols_on_mouth',
    '😈': 'smiling_face_with_horns',
    '👿': 'angry_face_with_horns',
    '💀': 'skull',
    '☠️': 'skull_and_crossbones',
    '💩': 'pile_of_poo',
    '🤡': 'clown_face',
    '👹': 'ogre',
    '👺': 'goblin',
    '👻': 'ghost',
    '👽': 'alien',
    '👾': 'alien_monster',
    '🤖': 'robot',
    '😺': 'grinning_cat',
    '😸': 'grinning_cat_with_smiling_eyes',
    '😹': 'cat_with_tears_of_joy',
    '😻': 'smiling_cat_with_heart_eyes',
    '😼': 'cat_with_wry_smile',
    '😽': 'kissing_cat',
    '🙀': 'weary_cat',
    '😿': 'crying_cat',
    '😾': 'pouting_cat',
    '❤️': 'red_heart',
    '🧡': 'orange_heart',
    '💛': 'yellow_heart',
    '💚': 'green_heart',
    '💙': 'blue_heart',
    '💜': 'purple_heart',
    '🖤': 'black_heart',
    '🤍': 'white_heart',
    '🤎': 'brown_heart',
    '💔': 'broken_heart',
    '❣️': 'heart_exclamation',
    '💕': 'two_hearts',
    '💞': 'revolving_hearts',
    '💓': 'beating_heart',
    '💗': 'growing_heart',
    '💖': 'sparkling_heart',
    '💘': 'heart_with_arrow',
    '💝': 'heart_with_ribbon',
    '💟': 'heart_decoration',
    '🔩': 'nut_and_bolt',
    '🎉': 'party_popper',
    '🎊': 'confetti_ball',
    '🎈': 'balloon',
    '🎂': 'birthday_cake',
    '🍰': 'shortcake',
    '🍮': 'pudding',
    '🍭': 'lollipop',
    '🍬': 'candy',
    '🍫': 'chocolate_bar',
    '🍿': 'popcorn',
    '🍩': 'doughnut',
    '🍪': 'cookie',
    '🍦': 'ice_cream',
    '🍧': 'shaved_ice',
    '🍨': 'ice_cream',
    '🍡': 'dango',
    '🥮': 'moon_cake',
    '🍥': 'fish_cake',
    '🍙': 'rice_cracker',
    '🍚': 'rice',
    '🍛': 'curry_rice',
    '🍜': 'steaming_bowl',
    '🍝': 'spaghetti',
    '🍕': 'pizza',
    '🍔': 'hamburger',
    '🍟': 'french_fries',
    '🌭': 'hot_dog',
    '🌮': 'taco',
    '🌯': 'burrito',
    '🥙': 'stuffed_flatbread',
    '🥗': 'green_salad',
    '🥘': 'shallow_pan_of_food',
    '🍲': 'pot_of_food',
    '🍱': 'bento_box',
    '🍣': 'sushi',
    '🍤': 'fried_shrimp',
    '🍙': 'rice_ball',
    '🍱': 'bento',
    '🍜': 'ramen',
    '🍲': 'stew',
    '🍛': 'curry',
    '🍣': 'sushi',
    '🍱': 'bento_box',
    '🥟': 'dumpling',
    '🥠': 'fortune_cookie',
    '🍝': 'spaghetti',
    '🍕': 'pizza',
    '🍔': 'hamburger',
    '🍟': 'fries',
    '🌭': 'hotdog',
    '🥪': 'sandwich',
    '🌮': 'taco',
    '🌯': 'burrito',
    '🥙': 'flatbread',
    '🧀': 'cheese_wedge',
    '🍳': 'cooking',
    '🥓': 'bacon',
    '🥩': 'cut_of_meat',
    '🍗': 'poultry_leg',
    '🍖': 'meat_on_bone',
    '🥩': 'cut_of_meat',
    '🍖': 'meat_on_bone',
    '🍗': 'roasted_chicken',
    '🥓': 'bacon',
    '🍳': 'fried_egg',
    '🥚': 'egg',
    '🥛': 'glass_of_milk',
    '☕': 'hot_beverage',
    '🍵': 'teacup_without_handle',
    '🍶': 'sake',
    '🍺': 'beer_mug',
    '🍷': 'wine_glass',
    '🥂': 'clinking_glasses',
    '🍹': 'tropical_drink',
    '🍸': 'cocktail_glass',
    '🍺': 'beer',
    '🍷': 'wine',
    '🥃': 'tumbler_glass',
    '🥤': 'cup_with_straw',
    '🧃': 'bubble_tea',
    '🧉': 'beverage_box',
    '🧊': 'ice_cube',
    '🍎': 'apple',
    '🍐': 'pear',
    '🍊': 'tangerine',
    '🍋': 'lemon',
    '🍌': 'banana',
    '🍉': 'watermelon',
    '🍇': 'grapes',
    '🍓': 'strawberry',
    '🍈': 'melon',
    '🍒': 'cherries',
    '🍑': 'peach',
    '🥭': 'mango',
    '🍍': 'pineapple',
    '🥥': 'coconut',
    '🥝': 'kiwi_fruit',
    '🍅': 'tomato',
    '🥑': 'avocado',
    '🍆': 'eggplant',
    '🥔': 'potato',
    '🥕': 'carrot',
    '🌽': 'ear_of_corn',
    '🌶️': 'hot_pepper',
    '🥒': 'cucumber',
    '🥬': 'leafy_green',
    '🥦': 'broccoli',
    '🧅': 'onion',
    '🧄': 'garlic',
    '🍄': 'mushroom',
    '🥜': 'peanuts',
    '🌰': 'chestnut',
    '🍯': 'honey_pot',
    '🥜': 'peanuts',
    '🌰': 'chestnut',
    '🍞': 'bread',
    '🥖': 'baguette_bread',
    '🥨': 'pretzel',
    '🧀': 'cheese',
    '🍖': 'meat_on_bone',
    '🍗': 'poultry_leg',
    '🥩': 'cut_of_meat',
    '🍖': 'meat_on_bone',
    '🍗': 'chicken',
    '🥓': 'bacon',
    '🍳': 'fried_egg',
    '🥚': 'egg',
    '🍳': 'cooking',
    '🥞': 'pancakes',
    '🧇': 'waffle',
    '🧈': 'butter',
    '🥛': 'milk',
    '🍼': 'baby_bottle',
    '☕': 'coffee',
    '🍵': 'tea',
    '🍶': 'sake',
    '🍺': 'beer',
    '🍷': 'wine',
    '🥛': 'milk',
    '🍺': 'beer_mug',
    '🍷': 'wine_glass',
    '🍹': 'cocktail',
    '🍸': 'tropical_drink',
    '🥤': 'cup_with_straw',
    '🧃': 'bubble_tea',
    '🧉': 'beverage_box',
    '🧊': 'ice',
    '🍴': 'fork_and_knife',
    '🍽️': 'fork_and_knife_with_plate',
    '🥄': 'spoon',
    '🔪': 'knife',
    '🏺': 'amphora',
    '🎨': 'artist_palette',
    '🖌️': 'paintbrush',
    '🖍️': 'crayon',
    '✏️': 'pencil',
    '✒️': 'black_nib',
    '📝': 'memo',
    '📚': 'books',
    '📖': 'open_book',
    '📕': 'green_book',
    '📗': 'blue_book',
    '📘': 'orange_book',
    '📙': 'book',
    '📔': 'notebook',
    '📒': 'ledger',
    '📓': 'notebook_with_decorative_cover',
    '📏': 'closed_book',
    '📐': 'triangular_ruler',
    '📓': 'notebook',
    '📔': 'notebook_with_decorative_cover',
    '📕': 'green_book',
    '📖': 'open_book',
    '📗': 'blue_book',
    '📘': 'orange_book',
    '📙': 'books',
    '📚': 'book',
    '📜': 'scroll',
    '📃': 'page_with_curl',
    '📄': 'page_facing_up',
    '📰': 'newspaper',
    '🗞️': 'rolled_up_newspaper',
    '📑': 'bookmark_tabs',
    '🏷️': 'label',
    '💼': 'briefcase',
    '📁': 'file_folder',
    '📂': 'open_file_folder',
    '🗂️': 'card_index_dividers',
    '📅': 'calendar',
    '📆': 'tear_off_calendar',
    '🗓️': 'spiral_calendar',
    '🗒️': 'spiral_note_pad',
    '📅': 'calendar',
    '🗃️': 'card_index_box',
    '📇': 'card_file_box',
    '📈': 'chart_increasing',
    '📉': 'chart_decreasing',
    '📊': 'bar_chart',
    '📋': 'clipboard',
    '📌': 'pushpin',
    '📍': 'round_pushpin',
    '📎': 'paperclip',
    '🖇️': 'linked_paperclips',
    '🧷': 'safety_pin',
    '📏': 'straight_ruler',
    '📐': 'triangular_ruler',
    '✂️': 'scissors',
    '🗃️': 'card_box',
    '📦': 'package',
    '📫': 'closed_mailbox_with_raised_flag',
    '📬': 'closed_mailbox_with_lowered_flag',
    '📭': 'open_mailbox_with_raised_flag',
    '📮': 'open_mailbox_with_lowered_flag',
    '📯': 'postal_horn',
    '📜': 'scroll',
    '📃': 'page_with_curl',
    '📄': 'page_facing_up',
    '📋': 'clipboard',
    '📁': 'file_folder',
    '📂': 'open_file_folder',
    '🗄️': 'file_cabinet',
    '📰': 'newspaper',
    '📑': 'notebook',
    '🔖': 'bookmark',
    '🏷️': 'label',
    '💰': 'money_bag',
    '💴': 'yen_banknote',
    '💵': 'dollar_banknote',
    '💶': 'euro_banknote',
    '💷': 'pound_banknote',
    '💸': 'money_with_wings',
    '💳': 'credit_card',
    '💎': 'gem_stone',
    '🎁': 'wrapped_gift',
    '🎈': 'balloon',
    '🎉': 'party_popper',
    '🎊': 'confetti_ball',
    '🎎': 'dolls',
    '🎏': 'flags',
    '🎐': 'wind_chime',
    '🧧': 'red_envelope',
    '🎀': 'ribbon',
    '🎗️': 'reminder_ribbon',
    '🎟️': 'admission_tickets',
    '🎫': 'ticket',
    '🎖️': 'military_medal',
    '🏆': 'trophy',
    '🏅': 'sports_medal',
    '🥇': '1st_place_medal',
    '🥈': '2nd_place_medal',
    '🥉': '3rd_place_medal',
    '🎗️': 'rosette',
    '🎁': 'gift',
    '🎉': 'party_popper',
    '🎊': 'confetti',
    '🎈': 'balloon',
    '🎂': 'birthday_cake',
    '🎮': 'video_game',
    '🎲': 'game_die',
    '🧩': 'jigsaw',
    '🎯': 'direct_hit',
    '🎳': 'bowling',
    '🏹': 'archery',
    '🎣': 'fishing_pole',
    '🎭': 'performing_arts',
    '🎨': 'art',
    '🎪': 'circus_tent',
    '🎤': 'microphone',
    '🎧': 'headphone',
    '🎼': 'musical_score',
    '🎹': 'musical_keyboard',
    '🥁': 'drum',
    '🪕': 'long_drum',
    '🎷': 'saxophone',
    '🎺': 'trumpet',
    '🎻': 'violin',
    '🪗': 'banjo',
    '🎵': 'musical_note',
    '🎶': 'musical_notes',
    '🎙️': 'studio_microphone',
    '🎚️': 'level_slider',
    '🎛️': 'control_knobs',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '📻': 'radio',
    '🎬': 'clapper_board',
    '🎥': 'cinema',
    '📽️': 'film_projector',
    '🎞️': 'film_frames',
    '📺': 'television',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'tv',
    '📻': 'radio',
    '🎮': 'video_game',
    '🎰': 'slot_machine',
    '🎲': 'game_die',
    '🧩': 'puzzle_piece',
    '🎯': 'bullseye',
    '🎳': 'bowling',
    '🏹': 'archery',
    '🎣': 'fishing_pole',
    '🎭': 'performing_arts',
    '🎪': 'circus_tent',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '🎵': 'musical_note',
    '🎶': 'notes',
    '🎼': 'musical_score',
    '🎹': 'keyboard',
    '🥁': 'drum',
    '🪕': 'long_drum',
    '🎷': 'saxophone',
    '🎺': 'trumpet',
    '🎻': 'violin',
    '🪗': 'banjo',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '📻': 'radio',
    '📺': 'television',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'television',
    '📡': 'satellite_antenna',
    '💻': 'laptop',
    '🖥️': 'desktop_computer',
    '🖨️': 'printer',
    '🖱️': 'mouse',
    '🖲️': 'trackball',
    '🕹️': 'joystick',
    '🎮': 'video_game',
    '💽': 'computer_disk',
    '💾': 'floppy_disk',
    '💿': 'optical_disk',
    '📀': 'dvd',
    '📼': 'videocassette',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'television',
    '📻': 'radio',
    '📱': 'mobile_phone',
    '☎️': 'telephone',
    '📞': 'telephone_receiver',
    '📟': 'pager',
    '📠': 'fax_machine',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '💡': 'light_bulb',
    '🔦': 'flashlight',
    '🕯️': 'candle',
    '💡': 'bulb',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '💻': 'laptop',
    '🖥️': 'desktop_computer',
    '🖨️': 'printer',
    '🖱️': 'mouse',
    '🖲️': 'trackball',
    '🕹️': 'joystick',
    '🎮': 'video_game',
    '💽': 'computer_disk',
    '💾': 'floppy_disk',
    '💿': 'cd',
    '📀': 'dvd',
    '📼': 'videocassette',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'television',
    '📻': 'radio',
    '📱': 'mobile_phone',
    '☎️': 'telephone',
    '📞': 'telephone_receiver',
    '📟': 'pager',
    '📠': 'fax',
    '⌨️': 'keyboard',
    '🖱️': 'mouse',
    '🖲️': 'trackball',
    '🕹️': 'joystick',
    '🎮': 'video_game',
    '💻': 'laptop',
    '🖥️': 'desktop_computer',
    '🖨️': 'printer',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '💡': 'light_bulb',
    '🔦': 'flashlight',
    '🕯️': 'candle',
    '💡': 'bulb',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '🚪': 'door',
    '🪟': 'window',
    '🛋️': 'couch_and_lamp',
    '🪑': 'chair',
    '🛏️': 'bed',
    '🛌': 'person_in_bed',
    '🧸': 'teddy_bear',
    '🧵': 'thread',
    '🧶': 'yarn',
    '🧣': 'scarf',
    '🧤': 'gloves',
    '🧥': 'coat',
    '🧦': 'socks',
    '👕': 't_shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'clutch_bag',
    '🛍️': 'shopping_bags',
    '🎒': 'backpack',
    '👓': 'eyeglasses',
    '🕶️': 'dark_sunglasses',
    '👔': 'necktie',
    '👔': 'tie',
    '👕': 'shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'pouch',
    '🛍️': 'shopping_bags',
    '🎒': 'school_satchel',
    '👞': 'mans_shoe',
    '👟': 'athletic_shoe',
    '👠': 'high_heeled_shoe',
    '👡': 'womans_sandal',
    '👢': 'womans_boots',
    '👣': 'footprints',
    '🧦': 'socks',
    '👒': 'womans_hat',
    '🎩': 'tophat',
    '👒': 'womans_hat',
    '👑': 'crown',
    '👒': 'hat',
    '🎩': 'top_hat',
    '👓': 'eyeglasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👒': 'womans_hat',
    '🎩': 'top_hat',
    '👓': 'glasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👔': 'necktie',
    '👔': 'tie',
    '👕': 't_shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'clutch_bag',
    '🛍️': 'shopping',
    '🎒': 'school_satchel',
    '👞': 'mans_shoe',
    '👟': 'running_shoe',
    '👠': 'womans_shoe',
    '👡': 'sandal',
    '👢': 'boot',
    '👣': 'footprints',
    '🧦': 'socks',
    '🧤': 'gloves',
    '🧥': 'coat',
    '🧣': 'scarf',
    '🧤': 'gloves',
    '🧦': 'socks',
    '👒': 'hat',
    '🎩': 'top_hat',
    '👓': 'glasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👑': 'crown',
    '👒': 'womans_hat',
    '🎩': 'top_hat',
    '👓': 'eyeglasses',
    '🕶️': 'dark_sunglasses',
    '👔': 'necktie',
    '👔': 'tie',
    '👕': 't_shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'pouch',
    '🛍️': 'shopping_bags',
    '🎒': 'backpack',
    '👞': 'mans_shoe',
    '👟': 'sneaker',
    '👠': 'high_heel',
    '👡': 'sandal',
    '👢': 'boot',
    '👣': 'footprints',
    '🧦': 'socks',
    '🧤': 'gloves',
    '🧥': 'coat',
    '🧣': 'scarf',
    '🧤': 'gloves',
    '🧦': 'socks',
    '👒': 'hat',
    '🎩': 'top_hat',
    '👓': 'glasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👑': 'crown',
    '🏠': 'house',
    '🏡': 'house_with_garden',
    '🏢': 'office_building',
    '🏣': 'japanese_post_office',
    '🏤': 'post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏯': 'japanese_castle',
    '🏰': 'castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🏣': 'post_office',
    '🏤': 'european_post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏯': 'japanese_castle',
    '🏰': 'european_castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🗿': 'moai',
    '🗽': 'statue_of_liberty',
    '🏗️': 'building_construction',
    '🧱': 'bricks',
    '🏘️': 'houses',
    '🏚️': 'derelict_house',
    '🏠': 'house',
    '🏡': 'house_with_garden',
    '🏢': 'office',
    '🏣': 'japanese_post_office',
    '🏤': 'european_post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏩': 'love_hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏰': 'castle',
    '🏯': 'japanese_castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🗿': 'moai',
    '🏗️': 'construction_site',
    '🧱': 'brick',
    '🏘️': 'housing_complex',
    '🏚️': 'abandoned_house',
    '🚧': 'construction',
    '🏗️': 'building_construction',
    '🧱': 'bricks',
    '🏘️': 'houses',
    '🏚️': 'derelict_house',
    '🏠': 'house',
    '🏡': 'house_with_garden',
    '🏢': 'office_building',
    '🏣': 'japanese_post_office',
    '🏤': 'european_post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏩': 'love_hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏰': 'castle',
    '🏯': 'japanese_castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🗿': 'moai',
    '🚧': 'construction',
    '🚦': 'traffic_light',
    '🛑': 'stop_sign',
    '🚧': 'construction',
    '🚥': 'horizontal_traffic_light',
    '🚦': 'vertical_traffic_light',
    '🛣️': 'highway',
    '🛤️': 'railway_track',
    '🗺️': 'world_map',
    '🗾': 'mount_fuji',
    '🗻': 'mountain',
    '🌋': 'volcano',
    '🗾': 'mount_fuji',
    '🏔️': 'mountain_snow',
    '🗻': 'mountain',
    '🌋': 'volcano',
    '🏔️': 'snow_capped_mountain',
    '🗾': 'mount_fuji',
    '🌅': 'sunrise',
    '🌄': 'sunrise_over_mountains',
    '🌇': 'sunset',
    '🌈': 'rainbow',
    '⛅': 'cloud',
    '🌤️': 'sun_behind_cloud',
    '🌥️': 'cloud_with_sun_behind',
    '🌦️': 'sun_behind_rain_cloud',
    '🌧️': 'rain_cloud',
    '🌨️': 'snow_cloud',
    '🌩️': 'lightning',
    '🌪️': 'tornado',
    '🌫️': 'fog',
    '🌬️': 'wind_blowing_face',
    '🌊': 'wave',
    '🌋': 'volcano',
    '🗻': 'mount_fuji',
    '🏔️': 'mountain_snow',
    '🌅': 'sunrise',
    '🌄': 'sunrise_over_mountains',
    '🌇': 'cityscape_at_dusk',
    '🌈': 'rainbow',
    '⛅': 'white_sun_with_cloud',
    '🌤️': 'sun_behind_cloud',
    '🌥️': 'cloud_with_sun_behind',
    '🌦️': 'sun_behind_rain_cloud',
    '🌧️': 'sun_behind_large_cloud',
    '🌨️': 'snow_cloud',
    '🌩️': 'thunder_cloud_and_rain',
    '🌪️': 'tornado',
    '🌫️': 'fog',
    '🌬️': 'wind_face',
    '🌊': 'ocean_wave',
    '🌌': 'foggy',
    '🎆': 'fireworks',
    '🎇': 'sparkler',
    '🧨': 'firecracker',
    '✨': 'sparkles',
    '💫': 'dizzy',
    '🌠': 'comet',
    '🎆': 'fireworks',
    '🎇': 'sparkler',
    '🧨': 'firecracker',
    '✨': 'sparkles',
    '💫': 'dizzy_stars',
    '🌠': 'shooting_star',
    '🌌': 'milky_way',
    '🌃': 'night_with_stars',
    '🌄': 'sunrise',
    '🌅': 'cityscape_at_dusk',
    '🌆': 'sunset_over_buildings',
    '🌇': 'bridge_at_night',
    '🌈': 'rainbow',
    '🌉': 'bridge_at_night',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '🗿': 'moai',
    '🏙️': 'cityscape',
    '🌃': 'cityscape_at_night',
    '🌄': 'sunrise_over_mountains',
    '🌅': 'sunrise',
    '🌆': 'cityscape',
    '🌇': 'sunset',
    '🌉': 'bridge_at_night',
    '🌁': 'foggy',
    '🌂️': 'closed_umbrella',
    '☔': 'umbrella_with_rain_drops',
    '⛱️': 'beach_with_umbrella',
    '🏖️': 'beach',
    '🏜️': 'desert',
    '🏝️': 'desert_island',
    '🏞️': 'national_park',
    '🌋': 'volcano',
    '🗻': 'mount_fuji',
    '🏔️': 'mountain_snow',
    '🌅': 'sunrise',
    '🌄': 'sunrise_over_mountains',
    '🌇': 'cityscape_at_dusk',
    '🌈': 'rainbow',
    '🌊': 'water_wave',
    '🌊': 'ocean_wave',
    '🌌': 'milky_way',
    '🌃': 'night_with_stars',
    '🌌': 'milky_way',
    '🎡': 'ferris_wheel',
    '🎢': 'roller_coaster',
    '🎠': 'carousel_horse',
    '🛷': 'sled',
    '🎿': 'skis',
    '⛷️': 'skier',
    '⛸️': 'ice_skate',
    '🏂': 'snowboarder',
    '🛹': 'skateboard',
    '🛼': 'roller_skate',
    '🚣': 'rowboat',
    '🚤': 'speedboat',
    '⛵': 'sailboat',
    '🛥️': 'motor_boat',
    '🚤': 'speedboat',
    '🛳️': 'passenger_ship',
    '⛴️': 'ferry',
    '🛳️': 'cruise_ship',
    '🚢': 'ship',
    '⚓': 'anchor',
    '🛥️': 'motorboat',
    '🚤': 'speedboat',
    '🛳️': 'passenger_ship',
    '⛵': 'sailboat',
    '🚣': 'rowboat',
    '🚣‍♂️': 'man_rowing_boat',
    '🚣‍♀️': 'woman_rowing_boat',
    '🏄': 'surfer',
    '🏄‍♂️': 'man_surfing',
    '🏄‍♀️': 'woman_surfing',
    '🏊': 'swimmer',
    '🏊‍♂️': 'man_swimming',
    '🏊‍♀️': 'woman_swimming',
    '⛹️': 'person_bouncing_ball',
    '🏀': 'basketball',
    '🏐': 'volleyball',
    '⚽': 'soccer_ball',
    '🏈': 'american_football',
    '🏉': 'rugby_football',
    '🎾': 'tennis',
    '🏓': 'ping_pong',
    '🏸': 'badminton',
    '🥊': 'boxing_glove',
    '🥋': 'martial_arts_uniform',
    '🎯': 'bullseye',
    '🎳': 'bowling',
    '🏹': 'archery',
    '🎣': 'fishing_pole',
    '🏊': 'swimmer',
    '🏊‍♂️': 'man_swimming',
    '🏊‍♀️': 'woman_swimming',
    '🤽': 'water_polo',
    '🤽‍♂️': 'man_playing_water_polo',
    '🤽‍♀️': 'woman_playing_water_polo',
    '🏌️': 'golfer',
    '🏌️‍♂️': 'man_golfing',
    '🏌️‍♀️': 'woman_golfing',
    '⛳': 'golf',
    '🏒': 'ice_hockey',
    '🏑': 'field_hockey',
    '🏏': 'cricket',
    '🎾': 'tennis',
    '🏸': 'badminton',
    '🏓': 'ping_pong',
    '🥊': 'boxing_glove',
    '🥋': 'martial_arts_uniform',
    '🎽': 'running_shirt_with_sash',
    '🏅': 'medal',
    '🥇': '1st_place_medal',
    '🥈': '2nd_place_medal',
    '🥉': '3rd_place_medal',
    '🏆': 'trophy',
    '🎖️': 'military_medal',
    '🏵️': 'rosette',
    '🎗️': 'reminder_ribbon',
    '🎫': 'ticket',
    '🎟️': 'admission_tickets',
    '🎪': 'circus_tent',
    '🎭': 'performing_arts',
    '🎨': 'art',
    '🎤': 'microphone',
    '🎧': 'headphone',
    '🎼': 'musical_score',
    '🎹': 'musical_keyboard',
    '🥁': 'drum',
    '🪕': 'long_drum',
    '🎷': 'saxophone',
    '🎺': 'trumpet',
    '🎻': 'violin',
    '🪗': 'banjo',
    '🎵': 'musical_note',
    '🎶': 'musical_notes',
    '🎙️': 'studio_microphone',
    '🎚️': 'level_slider',
    '🎛️': 'control_knobs',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '📻': 'radio',
    '🎬': 'clapper_board',
    '🎥': 'cinema',
    '📽️': 'film_projector',
    '🎞️': 'film_frames',
    '📺': 'television',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'tv',
    '📻': 'radio',
    '🎮': 'video_game',
    '🎰': 'slot_machine',
    '🎲': 'game_die',
    '🧩': 'jigsaw',
    '🎯': 'direct_hit',
    '🎳': 'bowling',
    '🏹': 'archery',
    '🎣': 'fishing_pole',
    '🎭': 'performing_arts',
    '🎪': 'circus_tent',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '🎵': 'musical_note',
    '🎶': 'musical_notes',
    '🎼': 'musical_score',
    '🎹': 'keyboard',
    '🥁': 'drum',
    '🪕': 'long_drum',
    '🎷': 'saxophone',
    '🎺': 'trumpet',
    '🎻': 'violin',
    '🪗': 'banjo',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '📻': 'radio',
    '📺': 'television',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'television',
    '📡': 'satellite_antenna',
    '💻': 'laptop',
    '🖥️': 'desktop_computer',
    '🖨️': 'printer',
    '🖱️': 'mouse',
    '🖲️': 'trackball',
    '🕹️': 'joystick',
    '🎮': 'video_game',
    '💽': 'computer_disk',
    '💾': 'floppy_disk',
    '💿': 'optical_disk',
    '📀': 'dvd',
    '📼': 'videocassette',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'television',
    '📻': 'radio',
    '📱': 'mobile_phone',
    '☎️': 'telephone',
    '📞': 'telephone_receiver',
    '📟': 'pager',
    '📠': 'fax_machine',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '💡': 'light_bulb',
    '🔦': 'flashlight',
    '🕯️': 'candle',
    '💡': 'bulb',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '🚪': 'door',
    '🪟': 'window',
    '🛋️': 'couch_and_lamp',
    '🪑': 'chair',
    '🛏️': 'bed',
    '🛌': 'person_in_bed',
    '🧸': 'teddy_bear',
    '🧵': 'thread',
    '🧶': 'yarn',
    '🧣': 'scarf',
    '🧤': 'gloves',
    '🧥': 'coat',
    '🧦': 'socks',
    '👕': 't_shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'clutch_bag',
    '🛍️': 'shopping_bags',
    '🎒': 'backpack',
    '👓': 'eyeglasses',
    '🕶️': 'dark_sunglasses',
    '👔': 'necktie',
    '👔': 'tie',
    '👕': 'shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'pouch',
    '🛍️': 'shopping_bags',
    '🎒': 'school_satchel',
    '👞': 'mans_shoe',
    '👟': 'athletic_shoe',
    '👠': 'high_heeled_shoe',
    '👡': 'womans_sandal',
    '👢': 'womans_boots',
    '👣': 'footprints',
    '🧦': 'socks',
    '👒': 'womans_hat',
    '🎩': 'tophat',
    '👒': 'womans_hat',
    '👑': 'crown',
    '👒': 'hat',
    '🎩': 'top_hat',
    '👓': 'eyeglasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👒': 'womans_hat',
    '🎩': 'top_hat',
    '👓': 'glasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👔': 'necktie',
    '👔': 'tie',
    '👕': 't_shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'clutch_bag',
    '🛍️': 'shopping',
    '🎒': 'school_satchel',
    '👞': 'mans_shoe',
    '👟': 'running_shoe',
    '👠': 'womans_shoe',
    '👡': 'sandal',
    '👢': 'boot',
    '👣': 'footprints',
    '🧦': 'socks',
    '🧤': 'gloves',
    '🧥': 'coat',
    '🧣': 'scarf',
    '🧤': 'gloves',
    '🧦': 'socks',
    '👒': 'hat',
    '🎩': 'top_hat',
    '👓': 'glasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👑': 'crown',
    '🏠': 'house',
    '🏡': 'house_with_garden',
    '🏢': 'office_building',
    '🏣': 'japanese_post_office',
    '🏤': 'post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏯': 'japanese_castle',
    '🏰': 'castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🏣': 'post_office',
    '🏤': 'european_post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏯': 'japanese_castle',
    '🏰': 'european_castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🗿': 'moai',
    '🏗️': 'building_construction',
    '🧱': 'bricks',
    '🏘️': 'houses',
    '🏚️': 'derelict_house',
    '🏠': 'house',
    '🏡': 'house_with_garden',
    '🏢': 'office',
    '🏣': 'japanese_post_office',
    '🏤': 'european_post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏩': 'love_hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏰': 'castle',
    '🏯': 'japanese_castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🗿': 'moai',
    '🏗️': 'construction_site',
    '🧱': 'brick',
    '🏘️': 'housing_complex',
    '🏚️': 'abandoned_house',
    '🚧': 'construction',
    '🏗️': 'building_construction',
    '🧱': 'bricks',
    '🏘️': 'houses',
    '🏚️': 'derelict_house',
    '🏠': 'house',
    '🏡': 'house_with_garden',
    '🏢': 'office_building',
    '🏣': 'japanese_post_office',
    '🏤': 'european_post_office',
    '🏥': 'hospital',
    '🏦': 'bank',
    '🏨': 'hotel',
    '🏩': 'love_hotel',
    '🏪': 'convenience_store',
    '🏫': 'school',
    '🏬': 'department_store',
    '🏭': 'factory',
    '🏰': 'castle',
    '🏯': 'japanese_castle',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '⛪': 'church',
    '🕌': 'mosque',
    '🕍': 'synagogue',
    '🕋': 'kaaba',
    '🗿': 'moai',
    '🚧': 'construction',
    '🚦': 'traffic_light',
    '🛑': 'stop_sign',
    '🚧': 'construction',
    '🚥': 'horizontal_traffic_light',
    '🚦': 'vertical_traffic_light',
    '🛣️': 'highway',
    '🛤️': 'railway_track',
    '🗺️': 'world_map',
    '🗾': 'mount_fuji',
    '🗻': 'mountain',
    '🌋': 'volcano',
    '🗾': 'mount_fuji',
    '🏔️': 'mountain_snow',
    '🗻': 'mountain',
    '🌋': 'volcano',
    '🏔️': 'snow_capped_mountain',
    '🗾': 'mount_fuji',
    '🌅': 'sunrise',
    '🌄': 'sunrise_over_mountains',
    '🌇': 'sunset',
    '🌈': 'rainbow',
    '⛅': 'cloud',
    '🌤️': 'sun_behind_cloud',
    '🌥️': 'cloud_with_sun_behind',
    '🌦️': 'sun_behind_rain_cloud',
    '🌧️': 'rain_cloud',
    '🌨️': 'snow_cloud',
    '🌩️': 'lightning',
    '🌪️': 'tornado',
    '🌫️': 'fog',
    '🌬️': 'wind_blowing_face',
    '🌊': 'wave',
    '🌋': 'volcano',
    '🗻': 'mount_fuji',
    '🏔️': 'mountain_snow',
    '🌅': 'sunrise',
    '🌄': 'sunrise_over_mountains',
    '🌇': 'cityscape_at_dusk',
    '🌈': 'rainbow',
    '⛅': 'white_sun_with_cloud',
    '🌤️': 'sun_behind_cloud',
    '🌥️': 'cloud_with_sun_behind',
    '🌦️': 'sun_behind_rain_cloud',
    '🌧️': 'sun_behind_large_cloud',
    '🌨️': 'snow_cloud',
    '🌩️': 'thunder_cloud_and_rain',
    '🌪️': 'tornado',
    '🌫️': 'fog',
    '🌬️': 'wind_face',
    '🌊': 'ocean_wave',
    '🌌': 'foggy',
    '🎆': 'fireworks',
    '🎇': 'sparkler',
    '🧨': 'firecracker',
    '✨': 'sparkles',
    '💫': 'dizzy',
    '🌠': 'comet',
    '🎆': 'fireworks',
    '🎇': 'sparkler',
    '🧨': 'firecracker',
    '✨': 'sparkles',
    '💫': 'dizzy_stars',
    '🌠': 'shooting_star',
    '🌌': 'milky_way',
    '🌃': 'night_with_stars',
    '🌄': 'sunrise',
    '🌅': 'cityscape_at_dusk',
    '🌆': 'sunset_over_buildings',
    '🌇': 'bridge_at_night',
    '🌈': 'rainbow',
    '🌉': 'bridge_at_night',
    '🗼': 'tokyo_tower',
    '🗽': 'statue_of_liberty',
    '🗿': 'moai',
    '🏙️': 'cityscape',
    '🌃': 'cityscape_at_night',
    '🌄': 'sunrise_over_mountains',
    '🌅': 'sunrise',
    '🌆': 'cityscape',
    '🌇': 'sunset',
    '🌉': 'bridge_at_night',
    '🌁': 'foggy',
    '🌂️': 'closed_umbrella',
    '☔': 'umbrella_with_rain_drops',
    '⛱️': 'beach_with_umbrella',
    '🏖️': 'beach',
    '🏜️': 'desert',
    '🏝️': 'desert_island',
    '🏞️': 'national_park',
    '🌋': 'volcano',
    '🗻': 'mount_fuji',
    '🏔️': 'mountain_snow',
    '🌅': 'sunrise',
    '🌄': 'sunrise_over_mountains',
    '🌇': 'cityscape_at_dusk',
    '🌈': 'rainbow',
    '🌊': 'water_wave',
    '🌊': 'ocean_wave',
    '🌌': 'milky_way',
    '🌃': 'night_with_stars',
    '🌌': 'milky_way',
    '🎡': 'ferris_wheel',
    '🎢': 'roller_coaster',
    '🎠': 'carousel_horse',
    '🛷': 'sled',
    '🎿': 'skis',
    '⛷️': 'skier',
    '⛸️': 'ice_skate',
    '🏂': 'snowboarder',
    '🛹': 'skateboard',
    '🛼': 'roller_skate',
    '🚣': 'rowboat',
    '🚤': 'speedboat',
    '⛵': 'sailboat',
    '🛥️': 'motor_boat',
    '🚤': 'speedboat',
    '🛳️': 'passenger_ship',
    '⛴️': 'ferry',
    '🛳️': 'cruise_ship',
    '🚢': 'ship',
    '⚓': 'anchor',
    '🛥️': 'motorboat',
    '🚤': 'speedboat',
    '🛳️': 'passenger_ship',
    '⛵': 'sailboat',
    '🚣': 'rowboat',
    '🚣‍♂️': 'man_rowing_boat',
    '🚣‍♀️': 'woman_rowing_boat',
    '🏄': 'surfer',
    '🏄‍♂️': 'man_surfing',
    '🏄‍♀️': 'woman_surfing',
    '🏊': 'swimmer',
    '🏊‍♂️': 'man_swimming',
    '🏊‍♀️': 'woman_swimming',
    '⛹️': 'person_bouncing_ball',
    '🏀': 'basketball',
    '🏐': 'volleyball',
    '⚽': 'soccer_ball',
    '🏈': 'american_football',
    '🏉': 'rugby_football',
    '🎾': 'tennis',
    '🏓': 'ping_pong',
    '🏸': 'badminton',
    '🥊': 'boxing_glove',
    '🥋': 'martial_arts_uniform',
    '🎯': 'bullseye',
    '🎳': 'bowling',
    '🏹': 'archery',
    '🎣': 'fishing_pole',
    '🏊': 'swimmer',
    '🏊‍♂️': 'man_swimming',
    '🏊‍♀️': 'woman_swimming',
    '🤽': 'water_polo',
    '🤽‍♂️': 'man_playing_water_polo',
    '🤽‍♀️': 'woman_playing_water_polo',
    '🏌️': 'golfer',
    '🏌️‍♂️': 'man_golfing',
    '🏌️‍♀️': 'woman_golfing',
    '⛳': 'golf',
    '🏒': 'ice_hockey',
    '🏑': 'field_hockey',
    '🏏': 'cricket',
    '🎾': 'tennis',
    '🏸': 'badminton',
    '🏓': 'ping_pong',
    '🥊': 'boxing_glove',
    '🥋': 'martial_arts_uniform',
    '🎽': 'running_shirt_with_sash',
    '🏅': 'medal',
    '🥇': '1st_place_medal',
    '🥈': '2nd_place_medal',
    '🥉': '3rd_place_medal',
    '🏆': 'trophy',
    '🎖️': 'military_medal',
    '🏵️': 'rosette',
    '🎗️': 'reminder_ribbon',
    '🎫': 'ticket',
    '🎟️': 'admission_tickets',
    '🎪': 'circus_tent',
    '🎭': 'performing_arts',
    '🎨': 'art',
    '🎤': 'microphone',
    '🎧': 'headphone',
    '🎼': 'musical_score',
    '🎹': 'musical_keyboard',
    '🥁': 'drum',
    '🪕': 'long_drum',
    '🎷': 'saxophone',
    '🎺': 'trumpet',
    '🎻': 'violin',
    '🪗': 'banjo',
    '🎵': 'musical_note',
    '🎶': 'musical_notes',
    '🎙️': 'studio_microphone',
    '🎚️': 'level_slider',
    '🎛️': 'control_knobs',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '📻': 'radio',
    '🎬': 'clapper_board',
    '🎥': 'cinema',
    '📽️': 'film_projector',
    '🎞️': 'film_frames',
    '📺': 'television',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'tv',
    '📻': 'radio',
    '🎮': 'video_game',
    '🎰': 'slot_machine',
    '🎲': 'game_die',
    '🧩': 'jigsaw',
    '🎯': 'direct_hit',
    '🎳': 'bowling',
    '🏹': 'archery',
    '🎣': 'fishing_pole',
    '🎭': 'performing_arts',
    '🎪': 'circus_tent',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '🎵': 'musical_note',
    '🎶': 'musical_notes',
    '🎼': 'musical_score',
    '🎹': 'keyboard',
    '🥁': 'drum',
    '🪕': 'long_drum',
    '🎷': 'saxophone',
    '🎺': 'trumpet',
    '🎻': 'violin',
    '🪗': 'banjo',
    '🎤': 'microphone',
    '🎧': 'headphones',
    '📻': 'radio',
    '📺': 'television',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'television',
    '📡': 'satellite_antenna',
    '💻': 'laptop',
    '🖥️': 'desktop_computer',
    '🖨️': 'printer',
    '🖱️': 'mouse',
    '🖲️': 'trackball',
    '🕹️': 'joystick',
    '🎮': 'video_game',
    '💽': 'computer_disk',
    '💾': 'floppy_disk',
    '💿': 'optical_disk',
    '📀': 'dvd',
    '📼': 'videocassette',
    '📷': 'camera',
    '📸': 'camera_with_flash',
    '📹': 'video_camera',
    '🎥': 'movie_camera',
    '📽️': 'film_projector',
    '🎬': 'clapper_board',
    '📺': 'television',
    '📻': 'radio',
    '📱': 'mobile_phone',
    '☎️': 'telephone',
    '📞': 'telephone_receiver',
    '📟': 'pager',
    '📠': 'fax_machine',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '💡': 'light_bulb',
    '🔦': 'flashlight',
    '🕯️': 'candle',
    '💡': 'bulb',
    '🔋': 'battery',
    '🔌': 'electric_plug',
    '🚪': 'door',
    '🪟': 'window',
    '🛋️': 'couch_and_lamp',
    '🪑': 'chair',
    '🛏️': 'bed',
    '🛌': 'person_in_bed',
    '🧸': 'teddy_bear',
    '🧵': 'thread',
    '🧶': 'yarn',
    '🧣': 'scarf',
    '🧤': 'gloves',
    '🧥': 'coat',
    '🧦': 'socks',
    '👕': 't_shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'clutch_bag',
    '🛍️': 'shopping_bags',
    '🎒': 'backpack',
    '👓': 'eyeglasses',
    '🕶️': 'dark_sunglasses',
    '👔': 'necktie',
    '👔': 'tie',
    '👕': 'shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'pouch',
    '🛍️': 'shopping_bags',
    '🎒': 'school_satchel',
    '👞': 'mans_shoe',
    '👟': 'athletic_shoe',
    '👠': 'high_heeled_shoe',
    '👡': 'womans_sandal',
    '👢': 'womans_boots',
    '👣': 'footprints',
    '🧦': 'socks',
    '👒': 'womans_hat',
    '🎩': 'tophat',
    '👒': 'womans_hat',
    '👑': 'crown',
    '👒': 'hat',
    '🎩': 'top_hat',
    '👓': 'eyeglasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👒': 'womans_hat',
    '🎩': 'top_hat',
    '👓': 'glasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👔': 'necktie',
    '👔': 'tie',
    '👕': 't_shirt',
    '👖': 'jeans',
    '👗': 'dress',
    '👘': 'kimono',
    '👙': 'bikini',
    '👚': 'womans_clothes',
    '👛': 'purse',
    '👜': 'handbag',
    '👝': 'clutch_bag',
    '🛍️': 'shopping',
    '🎒': 'school_satchel',
    '👞': 'mans_shoe',
    '👟': 'running_shoe',
    '👠': 'womans_shoe',
    '👡': 'sandal',
    '👢': 'boot',
    '👣': 'footprints',
    '🧦': 'socks',
    '🧤': 'gloves',
    '🧥': 'coat',
    '🧣': 'scarf',
    '🧤': 'gloves',
    '🧦': 'socks',
    '👒': 'hat',
    '🎩': 'top_hat',
    '👓': 'glasses',
    '🕶️': 'sunglasses',
    '🧢': 'billed_cap',
    '👑': 'crown'
  };

  const textToEmoji = Object.fromEntries(
    Object.entries(emojiToText).map(([emoji, text]) => [text, emoji])
  );

  const emojiRegex = /[\u{1F600}-\u{1F64F}]|[\u{1F300}-\u{1F5FF}]|[\u{1F680}-\u{1F6FF}]|[\u{1F1E0}-\u{1F1FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{1F900}-\u{1F9FF}]|[\u{1F018}-\u{1F270}]|[\u{238C}]|[\u{2000}-\u{200D}]|[\u{20D0}-\u{20FF}]|[\u{FE00}-\u{FE0F}]|[\u{1F200}-\u{1F2FF}]|[\u{1F780}-\u{1F7FF}]|[\u{1F800}-\u{1F8FF}]|🔩/gu;
  const shortcodeRegex = /:[a-zA-Z0-9_+-]+:/g;

  const formatText = (text: string): string => {
    let formatted = text.replace(/_/g, ' ');
    switch (caseMode) {
      case "lower":
        formatted = formatted.toLowerCase();
        break;
      case "upper":
        formatted = formatted.toUpperCase();
        break;
      case "title":
        formatted = formatted.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
        break;
      default:
        break;
    }
    if (addBrackets) {
      formatted = `[${formatted}]`;
    }
    return formatted;
  };

  const replaceEmojis = () => {
    if (!inputText.trim()) {
      toast({
        title: "Input Required",
        description: "Please enter text to process.",
        variant: "destructive",
      });
      return;
    }
    let result = inputText;
    let replacedCount = 0;

    if (replacementMode === "text") {
      result = result.replace(emojiRegex, (match) => {
        if (emojiToText[match]) {
          replacedCount++;
          return formatText(emojiToText[match]);
        }
        return match;
      });
      if (preserveShortcodes) {
        result = result.replace(shortcodeRegex, (match) => {
          const shortcode = match.slice(1, -1);
          if (textToEmoji[shortcode]) {
             replacedCount++;
             return formatText(shortcode);
          }
          return match;
        });
      }
    } else if (replacementMode === "emoji") {
      for (const [text, emoji] of Object.entries(textToEmoji)) {
        const words = text.split('_');
        const pattern = `\\b(${words.join('[\\s_&]*')})\\b`;
        const regex = new RegExp(pattern, 'gi');

        result = result.replace(regex, (match) => {
          replacedCount++;
          return emoji;
        });
        if (preserveShortcodes) {
          const shortcodePattern = new RegExp(`:${text}:`, 'gi');
          result = result.replace(shortcodePattern, (match) => {
            replacedCount++;
            return emoji;
          });
        }
      }
    } else if (replacementMode === "custom" && customReplacement.trim()) {
      const allEmojisRegex = new RegExp(`(${emojiRegex.source}|${shortcodeRegex.source})`, 'gu');
      result = result.replace(allEmojisRegex, () => {
        replacedCount++;
        return formatText(customReplacement);
      });
    }
    setOutputText(result);
    toast({
      title: "Replacement Complete",
      description: `Replaced ${replacedCount} instance${replacedCount !== 1 ? 's' : ''}.`,
    });
  };

  const copyToClipboard = async () => {
    if (!outputText) return;

    try {
      await navigator.clipboard.writeText(outputText);
      toast({
        title: "Copied!",
        description: "Converted text copied to clipboard.",
      });
    } catch (error) {
      toast({
        title: "Copy Failed",
        description: "Unable to copy to clipboard.",
        variant: "destructive",
      });
    }
  };

  const clearText = () => {
    setInputText("");
    setOutputText("");
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <Card>
        <CardContent className="p-6 space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <Label htmlFor="input-text">Input Text</Label>
                <Textarea
                  id="input-text"
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                  placeholder="Enter text with emojis or emoji descriptions..."
                  className="min-h-[200px] resize-none"
                />
              </div>
              <div className="space-y-4">
                <div>
                  <Label>Replacement Mode</Label>
                  <Select value={replacementMode} onValueChange={(value: "text" | "emoji" | "custom") => setReplacementMode(value)}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="text">Emoji to Text</SelectItem>
                      <SelectItem value="emoji">Text to Emoji</SelectItem>
                      <SelectItem value="custom">Custom Replacement</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                {replacementMode === "custom" && (
                  <div>
                    <Label htmlFor="custom-replacement">Custom Replacement Text</Label>
                    <Input
                      id="custom-replacement"
                      value={customReplacement}
                      onChange={(e) => setCustomReplacement(e.target.value)}
                      placeholder="Enter replacement text..."
                    />
                  </div>
                )}
                <div>
                  <Label>Text Formatting (for replacements)</Label>
                  <Select value={caseMode} onValueChange={(value: "keep" | "lower" | "upper" | "title") => setCaseMode(value)}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="keep">Keep Original Case</SelectItem>
                      <SelectItem value="lower">lowercase</SelectItem>
                      <SelectItem value="upper">UPPERCASE</SelectItem>
                      <SelectItem value="title">Title Case</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="preserve-shortcodes"
                      checked={preserveShortcodes}
                      onCheckedChange={(checked) => setPreserveShortcodes(checked as boolean)}
                    />
                    <Label htmlFor="preserve-shortcodes" className="text-sm">
                      Process shortcodes (e.g., :smile:)
                    </Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Checkbox
                      id="add-brackets"
                      checked={addBrackets}
                      onCheckedChange={(checked) => setAddBrackets(checked as boolean)}
                    />
                    <Label htmlFor="add-brackets" className="text-sm">
                      Add brackets to text [replacement]
                    </Label>
                  </div>
                </div>
              </div>
              <div className="flex flex-wrap gap-2">
                <Button onClick={replaceEmojis} className="flex items-center gap-2">
                  <RefreshCw className="w-4 h-4" />
                  Replace
                </Button>
                <Button variant="outline" onClick={clearText}>
                  Clear All
                </Button>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <Label htmlFor="output-text">Converted Text</Label>
                <Textarea
                  id="output-text"
                  value={outputText}
                  readOnly
                  placeholder="Converted text will appear here..."
                  className="min-h-[200px] resize-none bg-muted"
                />
              </div>
              <div className="flex flex-wrap gap-2">
                <Button
                  variant="outline"
                  onClick={copyToClipboard}
                  disabled={!outputText}
                  className="flex items-center gap-2"
                >
                  <Copy className="w-4 h-4" />
                  Copy Result
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default EmojiReplacer;
